version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    container_name: fakenews_web
    volumes:
      - ../web:/var/www
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "81:80"
  fakenews_py:
    build:
      context: .
      dockerfile: ./serverpy/Dockerfile
    container_name: fakenews_py
    volumes:
      - ../pkls:/var/www/pkls
      - ../server:/var/www/server
    ports:
      - "82:8080"