FROM nginx:1

#RUN apt-get update && apt-get install -y curl nodejs 

#RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
#RUN apt-get install -y nodejs
#RUN apt-get install -y build-essential 

WORKDIR /var/www
